# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://33x.ai" # the base hostname & protocol for your site

title: 33x.ai
description: >
  33x specializes in machine learning and robotics consulting.

  We help companies develop systematic and sustainable solutions for
  their data, machine learning, automation and robotics needs.

google_analytics: UA-7870337-1

# Build settings
exclude: ["Gemfile*", "Makefile", ".*"]
markdown: kramdown
